version: '3.7'
services:
    mysqldb:
        image: mysql
        restart: always
        environment:
          - MYSQL_USER=centrovax
          - MYSQL_PASSWORD=pa2022
          - MYSQL_DATABASE=centrovax
          - MYSQL_ROOT_PASSWORD=rootpassword
        ports:
          - '3306:3306'
        volumes: 
          # copy the sql script to create tables
          - ./seeder:/docker-entrypoint-initdb.d          
    node:
        build: .
        ports:
          - 8080:3000
        volumes:
          - './:/usr/src/app'
        environment:
          - MYSQL_HOST=mysqldb
        depends_on:
          - mysqldb
